# Generated by Django 2.1.1 on 2018-10-05 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('like_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Publish')),
            ],
        ),
        migrations.CreateModel(
            name='Likebyme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('like_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Post')),
            ],
        ),
    ]
